# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python


python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

install:
  - pip install -U pip pipenv
  - make dev

script:
  - make check
  - make test-unit
  - make requirements

after_success:
  coveralls

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  user: stibbons
  distributions: sdist bdist_wheel
  password:
    secure: !!binary |
      Rk00RGlnWTI0VW8xcUY1cGErQitqckc3S2Mrb1UvRnNOVElqdk5xUGFUOEdkdzJYR2JDeVAwd3Jj
      TG5Td2NEeVhpcHZXdzQwT0V3WS8zVUNidzhMc0JxTkZtQ1ZhaVBpQkpIL0hXZHZla2dUQ1lPSkpt
      Yld6RUl5NVRvNkRqcUhwdUY2ejBoTTFDUDdMSStEMllNMm51OE5NODBnVFp1MEM0RmR4M3FaQ3Q5
      YUxDbzBZcjZXV1BHNnVjYnN1ZFUzcWcyeHpIUVVKYk9xU0crbWJXd0lLalVSek5NbHNMeWdDWkhQ
      VDlDS0RIak8zL3hJZjN0akRUZUhTREJCdTkvUW9EeUNCc29FMUFIV2NXVGxKVjRZMnlRTExjTDNi
      MXkwNXYzT3NBYUlYbHpxMFJhbDM3Y0E2aWRkMWNtWU5iZGFOcXBXbjJ1b1c3M3RMV0JINTk4OEg4
      YkRXTHFIR290ZkdKaHVrOENveUYrSGtqUmtvaEk4Z2tIWEU5SzF3MDQxNlY1YTdTSU5qellybkZF
      M21MTlNVMVBXb1dMS2pNSzdPdFZNN0lrOEF0OWVlWFJuWmhxSDgrbzN5QlMzSnRqRGxRb3I0YURt
      ZytLOVh4ZmdzMHBwYy9zQ292bldjeGVKQ3Rvb1FmdVBEQURtSVBvVHBqWGx2LzY3ak5kYi9qOTY2
      NThPVHZ3eENnbnZQS09Sa2lxak9LK2kzRmFPdi9ra1VRNlRGMEZUODNFaVh1TFQzOTU4S3BZUzd4
      L3hRTks1bGxQV1kwQXFEcnJ1dDVkUThRSERSNklKMXFHaTdiUW1ia0VPTjVxa3BDcUhmSlhaRVgw
      V2JBT0F0UWpwUHBXcUgwSDA0c09iNi92dGlGM1lRbEVJTzQ0VU5LYXQyM0xtRTdGK0tXVEZPSXc9
  on:
    tags: true
    repo: Stibbons/txwebbackendbase
